<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>IDStack.Tests</RootNamespace>
    <AssemblyName>IDStack.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>Prabir kumar Das</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IDStack.Core\IDStack.Core.csproj" />
    <ProjectReference Include="..\IDStack\IDStack.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="NPOI" Version="2.6.2" />
  </ItemGroup>

</Project>
