<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>IDCardSoftware.Tests</RootNamespace>
    <AssemblyName>IDCardSoftware.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>theprabir</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IDCardSoftware.Core\IDCardSoftware.Core.csproj" />
    <ProjectReference Include="..\IDCardSoftware\IDCardSoftware.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
  </ItemGroup>

</Project>
